# Generated by Django 4.2.3 on 2023-07-18 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Select the assigned driver for this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='logistics.driver'),
        ),
    ]
