# Generated by Django 4.2.3 on 2023-09-28 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_vehicle_warehaouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='warehaouse',
            new_name='warehouse',
        ),
    ]
