# Generated by Django 4.2.3 on 2023-07-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_alter_job_assigned_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default=1, help_text="Enter the driver's phone number", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(default=1, help_text='Enter the license plate', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='device_gps',
            field=models.CharField(blank=True, help_text='Enter the device GPS information', max_length=100, null=True),
        ),
    ]
