# Generated by Django 4.2.3 on 2023-07-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_driver_phone_number_vehicle_license_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
