# Generated by Django 4.2.3 on 2023-11-01 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_remove_salesorder_trip_salesorder_visit'),
        ('logistics', '0009_drop_retrieve_payment_alter_drop_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='sales_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customervisit'),
        ),
    ]
