# Generated by Django 4.2.3 on 2023-11-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_remove_salesorder_trip_salesorder_visit'),
        ('logistics', '0010_drop_sales_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='trip',
            field=models.ForeignKey(help_text='Select the trip for this job', on_delete=django.db.models.deletion.CASCADE, to='sales.trip'),
        ),
        migrations.AlterField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(help_text='Select the vehicle for this job', on_delete=django.db.models.deletion.CASCADE, to='logistics.vehicle'),
        ),
    ]
