# Generated by Django 4.2.3 on 2024-03-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_delete_drivermovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
