# Generated by Django 4.2.3 on 2024-03-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_drop_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
    ]
