version: '3.8'

services:
  app:
    container_name: erp_services
    restart: always
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
#    ports:
#      - '127.0.0.1:8103:443'
#    image: 'strongpapazola/ubuntu:dr-mekanik'
    networks:
      - development

networks:
  development:
    name: development
    driver: bridge
##  docker-compose up -d --force-recreate --build
