version: "3.9"
services:
  db:
    container_name: postgis
    restart: always
#    image: mdillon/postgis
    image: postgis/postgis:14-3.3
    hostname: db
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "@Barakadut1234"
    volumes:
      - /opt/PGDATA:/var/lib/postgresql/data
    networks:
      - development
networks:
    development:
        name: development
        driver: bridge
