# Generated by Django 4.2.3 on 2023-07-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_file_owned_at_alter_file_owned_at_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='id62',
            new_name='id32',
        ),
    ]
