# Generated by Django 4.2.3 on 2023-11-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_file_approved_by_alter_file_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The name of the configuration setting', max_length=255, unique=True)),
                ('value', models.TextField(help_text='The value of the configuration setting')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
