# Generated by Django 4.2.3 on 2023-11-18 04:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='description',
            field=models.TextField(blank=True, help_text='The description of the configuration setting', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, max_length=300, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='http://127.0.0.1:8000/static/upload/file/', location='/Users/arifdzikrullah/Documents/Projects/erp/erp_backoffice/static/upload/file'), upload_to=''),
        ),
    ]
