# Generated by Django 4.2.3 on 2024-05-28 13:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0012_alter_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="Nonestatic/upload/file/",
                    location="/Users/fizi/Work/project/erp/erp_services/static/upload/file",
                ),
                upload_to="",
            ),
        ),
    ]
