# Generated by Django 4.2.3 on 2024-04-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0002_alter_brand_approved_by_alter_brand_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(blank=True, max_length=128, null=True)),
                ('id32', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('created_at_timestamp', models.PositiveIntegerField(db_index=True)),
                ('owned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owned_at_timestamp', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at_timestamp', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_at_timestamp', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('unpublished_at', models.DateTimeField(blank=True, null=True)),
                ('unpublished_at_timestamp', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at_timestamp', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('unapproved_at', models.DateTimeField(blank=True, null=True)),
                ('unapproved_at_timestamp', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at_timestamp', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='Name of the contact', max_length=100)),
                ('address', models.TextField(help_text="Contact's address")),
                ('contact_number', models.CharField(help_text="Contact's contact number", max_length=15)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='site',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='unapproved_by',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='unpublished_by',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='approved_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='company',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='created_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='deleted_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='id',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='id32',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='name',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='nonce',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='owned_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='owned_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='published_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='site',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='unapproved_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='unapproved_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='unapproved_by',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='unpublished_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='unpublished_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='unpublished_by',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='updated_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='updated_by',
        ),
    ]
