# Generated by Django 4.2.3 on 2023-07-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0003_alter_companyprofile_owned_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='id62',
            new_name='id32',
        ),
    ]
