# Generated by Django 4.2.3 on 2024-04-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0004_delete_companyprofile_contact_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(default='Contact', max_length=25),
        ),
    ]
