# Generated by Django 4.2.3 on 2023-08-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_rename_id62_file_id32'),
        ('identities', '0005_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company to which the brand belongs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='identities.companyprofile'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(help_text="Company's address"),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(help_text='Name of the company', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='contact_number',
            field=models.CharField(help_text="Company's contact number", max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(help_text='Biographical information about the user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(help_text="User's contact number", max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ForeignKey(blank=True, help_text='Profile picture for the user', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.file'),
        ),
    ]
