# Generated by Django 4.2.3 on 2024-04-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0005_contact_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(help_text="Contact's contact number", max_length=25),
        ),
    ]
