# Generated by Django 4.2.3 on 2024-05-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0006_alter_contact_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.CharField(blank=True, help_text='Enter account number', max_length=20, null=True, unique=True),
        ),
    ]
