# Generated by Django 4.2.3 on 2023-07-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_billofmaterials_owned_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billofmaterials',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='bomcomponent',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='productionorder',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='productiontracking',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='id62',
            new_name='id32',
        ),
    ]
