# Generated by Django 4.2.3 on 2023-07-13 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_stockmovement_options_and_more'),
        ('hr', '0003_rename_id62_attendance_id32_and_more'),
        ('production', '0003_rename_id62_billofmaterials_id32_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='components',
            field=models.ManyToManyField(related_name='used_in_bom', through='production.BOMComponent', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to='hr.employee', verbose_name='Assigned to'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
