# Generated by Django 4.2.3 on 2024-02-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_billofmaterials_product_billofmaterials_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomproduct',
            options={'verbose_name': 'BOM Product', 'verbose_name_plural': 'BOM Products'},
        ),
    ]
