# Generated by Django 4.2.3 on 2023-07-13 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_stockmovement_options_and_more'),
        ('production', '0004_alter_billofmaterials_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='work_center_warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
            preserve_default=False,
        ),
    ]
