# Generated by Django 4.2.3 on 2024-03-24 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_stockmovement_generate_items_from_sales'),
        ('production', '0005_rename_component_bomcomponent_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomcomponent',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bomproduct',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componentitem',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produceditem',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.unit'),
            preserve_default=False,
        ),
    ]
