# Generated by Django 4.2.3 on 2023-07-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_workorder_work_center_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
