# Generated by Django 4.2.3 on 2024-03-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_bomcomponent_unit_bomproduct_unit_componentitem_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produceditem',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
