# Generated by Django 4.2.3 on 2023-07-14 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_workorder_finished_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='finished_date',
            new_name='finished_time',
        ),
    ]
