# Generated by Django 4.2.3 on 2023-07-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_rename_finished_date_workorder_finished_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='finished_time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='workorder',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
