# Generated by Django 4.2.3 on 2024-03-24 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_stockmovement_generate_items_from_sales'),
        ('production', '0007_produceditem_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiontracking',
            name='work_center_warehouse',
            field=models.ForeignKey(blank=True, help_text='Select the warehouse for the work center', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
