# Generated by Django 4.2.3 on 2024-03-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_productiontracking_work_center_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produceditem',
            old_name='expired_date',
            new_name='expire_date',
        ),
    ]
