# Generated by Django 4.2.3 on 2023-07-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_rename_finished_time_workorder_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiontracking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
