# Generated by Django 4.2.3 on 2023-08-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_attendance_clock_in_time_and_more'),
        ('inventory', '0024_product_picture'),
        ('production', '0009_alter_productiontracking_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.OneToOneField(help_text='Select the main product for this BOM', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='bom',
            field=models.ForeignKey(help_text='Select the associated BOM', on_delete=django.db.models.deletion.CASCADE, to='production.billofmaterials'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='component',
            field=models.ForeignKey(help_text='Select the component product', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Enter the quantity of the component in the BOM', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='end_date',
            field=models.DateField(help_text='Enter the end date for the production order'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(help_text='Select the product for this production order', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Enter the quantity for the production order'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='start_date',
            field=models.DateField(help_text='Enter the start date for the production order'),
        ),
        migrations.AlterField(
            model_name='productiontracking',
            name='end_time',
            field=models.DateTimeField(help_text='Enter the end time for production tracking'),
        ),
        migrations.AlterField(
            model_name='productiontracking',
            name='produced_quantity',
            field=models.PositiveIntegerField(help_text='Enter the quantity produced'),
        ),
        migrations.AlterField(
            model_name='productiontracking',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Enter the start time for production tracking', null=True),
        ),
        migrations.AlterField(
            model_name='productiontracking',
            name='work_order',
            field=models.ForeignKey(help_text='Select the associated work order', on_delete=django.db.models.deletion.CASCADE, to='production.workorder'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Select the employee assigned to the work order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to='hr.employee', verbose_name='Assigned to'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Enter the end time for the work order', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='operation_number',
            field=models.PositiveIntegerField(help_text='Enter the operation number for the work order'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='production_order',
            field=models.ForeignKey(help_text='Select the associated production order', on_delete=django.db.models.deletion.CASCADE, to='production.productionorder'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Enter the start time for the work order', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_center',
            field=models.CharField(help_text='Enter the work center for the work order', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_center_warehouse',
            field=models.ForeignKey(help_text='Select the warehouse for the work center', on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
