# Generated by Django 4.2.3 on 2023-09-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='clock_in_coordinates',
            field=models.CharField(blank=True, help_text='Coordinates where the employee clocked in', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_coordinates',
            field=models.CharField(blank=True, help_text='Coordinates where the employee clocked out', max_length=255, null=True),
        ),
    ]
