# Generated by Django 4.2.3 on 2023-09-26 18:51

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_attendance_clock_in_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='clock_in_coordinates',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='clock_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='clock_out_coordinates',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='clock_out_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_in',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 18, 51, 46, 556067, tzinfo=datetime.timezone.utc), help_text='Clock-in time and date of the employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_in_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Coordinates where the employee clocked in', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out',
            field=models.DateTimeField(blank=True, help_text='Clock-out time and date of the employee', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='clock_out_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Coordinates where the employee clocked out', null=True, srid=4326),
        ),
    ]
