# Generated by Django 4.2.3 on 2023-07-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_attendance_owned_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='id62',
            new_name='id32',
        ),
    ]
