# Generated by Django 4.2.3 on 2023-08-10 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0003_rename_id62_attendance_id32_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='clock_in_time',
            field=models.TimeField(help_text='Clock-in time of the employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='clock_out_time',
            field=models.TimeField(help_text='Clock-out time of the employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(help_text='Date of attendance'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(help_text='The employee whose attendance is recorded', on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='The name of the department', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department the employee belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(help_text='The associated user of the employee', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(help_text='The employee who requested the leave', on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(help_text='End date of the leave'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(help_text='The type of leave', max_length=100),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(help_text='Start date of the leave'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='The status of the leave request', max_length=20),
        ),
        migrations.AlterField(
            model_name='performance',
            name='employee',
            field=models.ForeignKey(help_text='The employee being reviewed', on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text="Rating given to the employee's performance"),
        ),
        migrations.AlterField(
            model_name='performance',
            name='review',
            field=models.TextField(blank=True, help_text='Additional review notes'),
        ),
    ]
