# Generated by Django 4.2.3 on 2023-10-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_attendance_clock_in_coordinates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='able_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
