# Generated by Django 4.2.3 on 2023-12-06 07:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_locationtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Coordinates where the employee currently located', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='locationtracker',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Coordinates where the employee located', null=True, srid=4326),
        ),
    ]
