# Generated by Django 4.2.3 on 2023-12-06 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_employee_last_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtracker',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='The employee being traked', on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
    ]
