# Generated by Django 4.2.3 on 2023-12-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_alter_locationtracker_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtracker',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='The employee being traked', null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
    ]
