# Generated by Django 4.2.3 on 2024-06-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0012_employee_basic_salary_salary"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bank_account_number",
            field=models.CharField(
                blank=True,
                help_text="Enter the employee's bank account number",
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="basic_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Enter the employee's basic salary amount",
                max_digits=19,
            ),
        ),
    ]
