# Generated by Django 4.2.3 on 2023-10-03 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.unit'),
            preserve_default=False,
        ),
    ]
