# Generated by Django 4.2.3 on 2023-07-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_quantity_productlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLog',
        ),
    ]
