# Generated by Django 4.2.3 on 2023-10-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_warehousestock_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementitem',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
