# Generated by Django 4.2.3 on 2023-10-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_expired_at_stockmovementitem_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('canceled', 'Canceled'), ('preparing', 'Preparing'), ('ready', 'Ready to pickup'), ('on_delivery', 'On Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned')], default='requested', max_length=20),
        ),
    ]
