# Generated by Django 4.2.3 on 2023-07-12 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_warehouse_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='from_warehouse_id',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='from_warehouse_type',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='to_warehouse_id',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='to_warehouse_type',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_stockmovement_set', related_query_name='from_stockmovement', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_stockmovement_set', related_query_name='to_stockmovement', to='inventory.warehouse'),
        ),
    ]
