# Generated by Django 4.2.3 on 2023-07-12 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0007_remove_stockmovement_from_warehouse_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='from_warehouse',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='to_location',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='to_warehouse',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_warehouse_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_warehouse_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_stockmovement_set', related_query_name='from_stockmovement', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_warehouse_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_warehouse_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_stockmovement_set', related_query_name='to_stockmovement', to='contenttypes.contenttype'),
        ),
    ]
