# Generated by Django 4.2.3 on 2023-10-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockmovement_creator_id_stockmovement_creator_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sales_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_unit',
        ),
    ]
