# Generated by Django 4.2.3 on 2023-07-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_stockmovement_from_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
