# Generated by Django 4.2.3 on 2023-10-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovementitem',
            options={'ordering': ['order'], 'verbose_name': 'Stock Movement Item', 'verbose_name_plural': 'Stock Movement Items'},
        ),
        migrations.AddField(
            model_name='stockmovementitem',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
