# Generated by Django 4.2.3 on 2023-07-12 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0009_alter_stockmovement_movement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Enter the category description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Enter the category name', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Select the product category', on_delete=django.db.models.deletion.CASCADE, to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Enter the product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Enter the product name', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(help_text='Enter the product quantity'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Specify the creation date'),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='created_by',
            field=models.ForeignKey(help_text='Select the user who created the log', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='product',
            field=models.ForeignKey(help_text='Select the product associated with the log', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='replenishmentorder',
            name='order_date',
            field=models.DateField(help_text='Specify the order date'),
        ),
        migrations.AlterField(
            model_name='replenishmentorder',
            name='product',
            field=models.ForeignKey(help_text='Select the product', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='replenishmentorder',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Enter the quantity'),
        ),
        migrations.AlterField(
            model_name='replenishmentreceived',
            name='received_date',
            field=models.DateField(help_text='Specify the received date'),
        ),
        migrations.AlterField(
            model_name='replenishmentreceived',
            name='replenishment_order',
            field=models.ForeignKey(help_text='Select the replenishment order', on_delete=django.db.models.deletion.CASCADE, to='inventory.replenishmentorder'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_date',
            field=models.DateField(help_text='Specify the adjustment date'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(help_text='Select the product', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity',
            field=models.IntegerField(help_text='Enter the quantity'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.TextField(blank=True, help_text='Enter the reason for the adjustment'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='from_warehouse_id',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the ID of the source warehouse', null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='from_warehouse_type',
            field=models.ForeignKey(blank=True, help_text='Select the content type of the source warehouse', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_stockmovement_set', related_query_name='from_stockmovement', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_date',
            field=models.DateTimeField(blank=True, help_text='Specify the movement date', null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(help_text='Select the product', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(help_text='Enter the quantity'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='to_warehouse_id',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the ID of the destination warehouse', null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='to_warehouse_type',
            field=models.ForeignKey(blank=True, help_text='Select the content type of the destination warehouse', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_stockmovement_set', related_query_name='to_stockmovement', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(help_text='Enter the warehouse name', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='product',
            field=models.ForeignKey(help_text='Select the product', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Enter the product quantity in the warehouse'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='warehouse',
            field=models.ForeignKey(help_text='Select the warehouse', on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse'),
        ),
    ]
