# Generated by Django 4.2.3 on 2023-07-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_warehouse_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name': 'Stock Movement', 'verbose_name_plural': 'Stock Movements'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='replenishmentorder',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='replenishmentreceived',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='stockadjustment',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='warehousestock',
            old_name='id62',
            new_name='id32',
        ),
    ]
