# Generated by Django 4.2.3 on 2023-10-21 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0013_stockmovementitem_destination_checked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='pic',
            field=models.ManyToManyField(blank=True, help_text='Select people in charge of this warehouse', to=settings.AUTH_USER_MODEL),
        ),
    ]
