# Generated by Django 4.2.3 on 2023-07-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_warehousestock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Requested'), (2, 'Preparing'), (3, 'On Delivery'), (4, 'Delivered'), (5, 'Canceled'), (6, 'Returned')], default=1),
        ),
    ]
