# Generated by Django 4.2.3 on 2023-07-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stockmovement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Requested'), (2, 'Canceled'), (3, 'Preparing'), (4, 'On Delivery'), (5, 'Delivered'), (6, 'Returned')], default=1),
        ),
    ]
