# Generated by Django 4.2.3 on 2023-10-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_stockmovement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('canceled', 'Canceled'), ('preparing', 'Preparing'), ('ready', 'Ready to Deliver'), ('on_delivery', 'On Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('on_check', 'On Check in destination'), ('checked', 'Checked in destination'), ('put', 'Has been put in destination warehouse')], default='requested', max_length=20),
        ),
    ]
