# Generated by Django 4.2.3 on 2023-07-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_stockmovement_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='to_warehouse_id',
            new_name='destionation_id',
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='to_warehouse_type',
            new_name='destionation_type',
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='from_warehouse_id',
            new_name='origin_id',
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='from_warehouse_type',
            new_name='origin_type',
        ),
    ]
