# Generated by Django 4.2.3 on 2023-10-24 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_file_approved_by_alter_file_deleted_by_and_more'),
        ('inventory', '0017_alter_stockmovement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='movement_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_movement_evidence', to='common.file'),
        ),
    ]
