# Generated by Django 4.2.3 on 2023-07-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_rename_to_warehouse_id_stockmovement_destionation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='destionation_id',
            new_name='destination_id',
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='destionation_type',
            new_name='destination_type',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Requested'), (2, 'Canceled'), (3, 'Preparing'), (4, 'Ready to pickup'), (5, 'On Delivery'), (6, 'Delivered'), (7, 'Returned')], default=1),
        ),
    ]
