# Generated by Django 4.2.3 on 2023-10-28 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_remove_invalidpoitem_actual_price_and_more'),
        ('inventory', '0019_stockmovementitem_po_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementitem',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchasing.purchaseorderitem'),
        ),
    ]
