# Generated by Django 4.2.3 on 2023-07-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_stockmovement_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementitem',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Enter the quantity'),
        ),
    ]
