# Generated by Django 4.2.3 on 2023-10-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_stockmovementitem_po_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Enter the product stock keeping unit or barcode', max_length=100, unique=True),
        ),
    ]
