# Generated by Django 4.2.3 on 2023-11-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price in IDR (Rp)', max_digits=19),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_buy_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Last buy price in IDR (Rp)', max_digits=19),
        ),
        migrations.AlterField(
            model_name='product',
            name='margin_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the value for margin (0-1 for percentage, >0 for fixed)', max_digits=19),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sell price in IDR (Rp)', max_digits=19),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='base_price_change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the base price change', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='buy_price_change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the buy price change', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='sell_price_change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the base price change', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('canceled', 'Canceled'), ('preparing', 'Preparing by picker'), ('verifying', 'Verifying by checker'), ('ready', 'Ready to Deliver'), ('on_delivery', 'On Delivery'), ('delivered', 'Delivered to destination'), ('returned', 'Returned'), ('on_check', 'On Check in destination'), ('checked', 'Checked in destination'), ('put', 'Has been put in destination warehouse')], default='requested', max_length=20),
        ),
    ]
