# Generated by Django 4.2.3 on 2023-08-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_product_alias_product_brand_product_minimum_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='level',
            field=models.PositiveIntegerField(default=0, help_text='Unit depth level'),
        ),
    ]
