# Generated by Django 4.2.3 on 2023-08-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_unit_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base price in IDR (Rp)', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Check if this product is active'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_buy_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Last buy price in IDR (Rp)', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_calculation',
            field=models.CharField(choices=[('fifo', 'FIFO - First in first out of buy price history'), ('lifo', 'LIFO - Last in first out of buy price history'), ('average', 'Average - Average of buy price history'), ('production_cost', 'Production Cost - Form direct material cost, labour cost, and manufacturing overhead')], default='fifo', help_text='Select on how the base price will be calculated', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sell price in IDR (Rp)', max_digits=10),
            preserve_default=False,
        ),
    ]
