# Generated by Django 4.2.3 on 2024-02-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_stockmovementitem_destination_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_calculation',
            field=models.CharField(choices=[('manual', 'Manually calculated'), ('fifo', 'FIFO - First in first out of buy price history'), ('lifo', 'LIFO - Last in first out of buy price history'), ('average', 'Average - Average of buy price history'), ('production_cost', 'Production Cost - Form direct material cost, labour cost, and manufacturing overhead')], help_text='Select on how the base price will be calculated', max_length=20),
        ),
    ]
