# Generated by Django 4.2.3 on 2024-03-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_product_price_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='generate_items_from_sales',
            field=models.BooleanField(default=True),
        ),
    ]
