# Generated by Django 4.2.3 on 2023-08-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovementitem',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Buy price', max_digits=10, null=True),
        ),
    ]
