# Generated by Django 4.2.3 on 2024-03-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_alter_product_price_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_str',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Enter the product stock keeping unit or barcode', max_length=100, null=True),
        ),
    ]
