# Generated by Django 4.2.3 on 2023-08-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_productlog_base_price_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlog',
            name='sell_price_change',
            field=models.IntegerField(blank=True, help_text='Enter the base price change', null=True),
        ),
    ]
