# Generated by Django 4.2.3 on 2023-08-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_productlog_sell_price_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlog',
            name='base_price_change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the base price change', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='buy_price_change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the buy price change', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='sell_price_change',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the base price change', max_digits=10, null=True),
        ),
    ]
