# Generated by Django 4.2.3 on 2023-08-13 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_alter_productlog_base_price_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='movement_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockmovementitem'),
        ),
    ]
