# Generated by Django 4.2.3 on 2023-08-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_warehousestock_movement_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousestock',
            name='movement_item',
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='movement_items',
            field=models.ManyToManyField(blank=True, to='inventory.stockmovementitem'),
        ),
    ]
