# Generated by Django 4.2.3 on 2023-08-13 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_remove_warehousestock_movement_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousestock',
            name='movement_items',
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='dispatch_movement_items',
            field=models.ManyToManyField(blank=True, related_name='dispatch_stock_items', to='inventory.stockmovementitem'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='inbound_movement_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_stock_item', to='inventory.stockmovementitem'),
        ),
    ]
