# Generated by Django 4.2.3 on 2023-08-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_remove_warehousestock_movement_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Last buy price in IDR (Rp)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Sell price in IDR (Rp)', max_digits=10, null=True),
        ),
    ]
