# Generated by Django 4.2.3 on 2023-08-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='margin_type',
            field=models.CharField(choices=[('percentage', 'Percentage margin value from base price'), ('fixed', 'Fixed margin value')], default='fixed', help_text='Select on how the margin will be calculated', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='margin_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the value for margin (0-1 for percentage, >0 for fixed)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_buy_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Last buy price in IDR (Rp)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sell price in IDR (Rp)', max_digits=10),
        ),
    ]
