# Generated by Django 4.2.3 on 2023-08-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_product_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('canceled', 'Canceled'), ('preparing', 'Preparing'), ('ready', 'Ready to pickup'), ('on_delivery', 'On Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned')], max_length=20),
        ),
    ]
