# Generated by Django 4.2.3 on 2023-08-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_stockmovementitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementitem',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Buy price', max_digits=19, null=True),
        ),
    ]
