# Generated by Django 4.2.3 on 2023-08-22 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_alter_stockmovementitem_buy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Conversion factor to parent unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
    ]
