# Generated by Django 4.2.3 on 2023-08-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_id62_account_id32_rename_id62_activity_id32_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(help_text='The address of the account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(help_text='The email of the account', max_length=254),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='The name of the account', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(help_text='The phone number of the account', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='due_date',
            field=models.DateField(help_text='The due date of the activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='planned', help_text='The status of the activity', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('task', 'Task'), ('other', 'Other')], help_text='The type of the activity', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='The email of the contact', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(help_text='The first name of the contact', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(help_text='The last name of the contact', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(help_text='The phone number of the contact', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(help_text='The email of the lead', max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(help_text='The name of the lead', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(help_text='The phone number of the lead', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(help_text='The source from where the lead originated', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', help_text='The status of the lead', max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='account',
            field=models.ForeignKey(help_text='The associated account of the opportunity', on_delete=django.db.models.deletion.CASCADE, to='crm.account'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(help_text='The name of the opportunity', max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='probability',
            field=models.PositiveIntegerField(help_text='The probability percentage of closing the opportunity'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed', 'Closed')], help_text='The stage of the opportunity', max_length=100),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='The value of the opportunity', max_digits=10),
        ),
    ]
