# Generated by Django 4.2.3 on 2023-10-07 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0001_initial'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='company_profile',
            field=models.ForeignKey(blank=True, help_text='Select the company profile for this supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_profile', to='identities.companyprofile', verbose_name='Company Profile'),
        ),
    ]
