# Generated by Django 4.2.3 on 2023-10-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_alter_supplier_company_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-id'], 'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['-id'], 'verbose_name': 'Purchase Order Item', 'verbose_name_plural': 'Purchase Order Items'},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-id'], 'verbose_name': 'Shipment', 'verbose_name_plural': 'Shipments'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-id'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='supplierproduct',
            options={'ordering': ['-id'], 'verbose_name': 'Supplier Product', 'verbose_name_plural': 'Supplier Products'},
        ),
        migrations.AlterModelOptions(
            name='vendorperformance',
            options={'ordering': ['-id'], 'verbose_name': 'Vendor Performance', 'verbose_name_plural': 'Vendor Performances'},
        ),
    ]
