# Generated by Django 4.2.3 on 2023-07-12 10:21

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_category_owned_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchasing', '0004_remove_productlog_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Specify the date and time of approval', null=True, verbose_name='Approved at'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Select the user who approved the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(help_text='Enter the order date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(help_text='Select the supplier associated with the order', on_delete=django.db.models.deletion.CASCADE, to='purchasing.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the item price in IDR (Rp)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(help_text='Select the product associated with the item', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(help_text='Select the purchase order associated with the item', on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Enter the item quantity'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='purchase_order',
            field=models.ForeignKey(help_text='Select the purchase order associated with the shipment', on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(help_text='Enter the shipment date'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(help_text='Enter the address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_number',
            field=models.CharField(help_text='Enter the contact number', max_length=15),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Enter the location coordinates', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text="Enter the supplier's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='comments',
            field=models.TextField(blank=True, help_text='Enter any comments or additional information'),
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text='Select the rating for the vendor performance'),
        ),
        migrations.AlterField(
            model_name='vendorperformance',
            name='supplier',
            field=models.ForeignKey(help_text='Select the supplier associated with the vendor performance', on_delete=django.db.models.deletion.CASCADE, to='purchasing.supplier'),
        ),
    ]
