# Generated by Django 4.2.3 on 2023-10-22 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_stockmovement_status'),
        ('purchasing', '0004_alter_purchaseorder_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
    ]
