# Generated by Django 4.2.3 on 2023-10-29 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_file_approved_by_alter_file_deleted_by_and_more'),
        ('purchasing', '0007_remove_invalidpoitem_actual_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='invalid_item_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_invalid_item_evidence', to='common.file'),
        ),
    ]
