# Generated by Django 4.2.3 on 2024-03-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0009_alter_invalidpoitem_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the discount amount for purchase order', max_digits=19),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the tax amount for purchase order', max_digits=19),
        ),
    ]
