# Generated by Django 4.2.3 on 2023-08-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0010_alter_supplierproduct_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='price',
            new_name='po_price',
        ),
    ]
