# Generated by Django 4.2.3 on 2024-05-14 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0010_purchaseorder_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="billing_due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="down_payment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Enter the DP amount",
                max_digits=19,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="payment_term",
            field=models.IntegerField(
                choices=[
                    (0, "Tunai"),
                    (7, "7 Hari"),
                    (14, "14 Hari"),
                    (21, "21 Hari"),
                    (30, "1 Bulan"),
                ],
                default=0,
                help_text="Enter payment term to decide billing date Purchase Order",
            ),
        ),
    ]
