# Generated by Django 4.2.3 on 2023-08-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0011_rename_price_purchaseorderitem_po_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the actual item price', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='po_price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the purchase order item price', max_digits=10),
        ),
    ]
