# Generated by Django 4.2.3 on 2024-04-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0005_contact_role'),
        ('purchasing', '0011_alter_supplier_company_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='approved_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='deleted_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='id32',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='nonce',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='owned_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='owned_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='owned_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='published_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='site',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='unapproved_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='unapproved_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='unapproved_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='unpublished_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='unpublished_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='unpublished_by',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='identities.contact'),
            preserve_default=False,
        ),
    ]
