# Generated by Django 4.2.3 on 2024-04-21 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0012_remove_supplier_address_remove_supplier_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='company_profile',
        ),
    ]
