# Generated by Django 4.2.3 on 2023-08-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0012_purchaseorderitem_actual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the actual item price', max_digits=10, null=True),
        ),
    ]
