# Generated by Django 4.2.3 on 2023-08-13 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_stockmovementitem_buy_price'),
        ('purchasing', '0013_alter_purchaseorderitem_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockmovement'),
        ),
    ]
