# Generated by Django 4.2.3 on 2024-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0014_purchaseorder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='has_payable',
            field=models.BooleanField(default=False),
        ),
    ]
