# Generated by Django 4.2.3 on 2023-08-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0015_purchaseorderitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='po_price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the purchase order item price', max_digits=19),
        ),
    ]
