
WAITING = 'waiting'
ON_PROGRESS = 'on_progress'
ARRIVED = 'arrived'
COMPLETED = 'completed'
SKIPPED = 'skipped'

VAT_DEFAULT = 0.11

CANVASING_MOBILE_MENU = 'sales_canvasing'
TAKING_ORDER_MOBILE_MENU = 'sales_taking_order'
SALES_ORDER_MOBILE_MENU = 'sales_order'
SALES_REPORT_MOBILE_MENU = 'sales_report'
CUSTOMER_MOBILE_MENU = 'customer'
PICKER_MOBILE_MENU = 'picker'
CHECKER_MOBILE_MENU = 'checker'
STOCK_MOBILE_MENU = 'stock'
DELIVERY_MOBILE_MENU = 'delivery'
COLLECTION_MOBILE_MENU = 'collection'

PRODUCT_MOBILE_MENU = 'product'
BOM_MOBILE_MENU = 'bom'
WORKORDER_MOBILE_MENU = 'work_order'
PRODUCTION_MOBILE_MENU = 'production'
PROCEED_ITEM_MOBILE_MENU = 'proceed_item'
STOCK_MOBILE_MENU = 'stock'
STOCK_MOVEMENT_MOBILE_MENU = 'stock_movement'


MOBILE_ROLE_MENU_MAP = (
# Rizz
    ('sales-canvasing', [CANVASING_MOBILE_MENU, SALES_ORDER_MOBILE_MENU, CUSTOMER_MOBILE_MENU, STOCK_MOBILE_MENU]),
    ('sales-taking-order', [TAKING_ORDER_MOBILE_MENU, SALES_ORDER_MOBILE_MENU, CUSTOMER_MOBILE_MENU, STOCK_MOBILE_MENU]),
    ('picker', [PICKER_MOBILE_MENU, STOCK_MOBILE_MENU]),
    ('checker', [CHECKER_MOBILE_MENU, STOCK_MOBILE_MENU]),
    ('driver', [DELIVERY_MOBILE_MENU]),
    ('collector', [COLLECTION_MOBILE_MENU]),
# HJK
    ('sales', [PRODUCT_MOBILE_MENU, SALES_ORDER_MOBILE_MENU, CUSTOMER_MOBILE_MENU, SALES_REPORT_MOBILE_MENU]),
    ('production', [PRODUCT_MOBILE_MENU, BOM_MOBILE_MENU, WORKORDER_MOBILE_MENU, PRODUCTION_MOBILE_MENU]),
    ('warehouse', [PRODUCT_MOBILE_MENU, PROCEED_ITEM_MOBILE_MENU, STOCK_MOBILE_MENU, STOCK_MOVEMENT_MOBILE_MENU]),
    ('branch_manager', [PRODUCT_MOBILE_MENU, SALES_ORDER_MOBILE_MENU, CUSTOMER_MOBILE_MENU, SALES_REPORT_MOBILE_MENU, BOM_MOBILE_MENU, WORKORDER_MOBILE_MENU, PRODUCTION_MOBILE_MENU, PROCEED_ITEM_MOBILE_MENU, STOCK_MOBILE_MENU, STOCK_MOVEMENT_MOBILE_MENU]),
    ('owner', [PRODUCT_MOBILE_MENU, SALES_ORDER_MOBILE_MENU, CUSTOMER_MOBILE_MENU, SALES_REPORT_MOBILE_MENU, BOM_MOBILE_MENU, WORKORDER_MOBILE_MENU, PRODUCTION_MOBILE_MENU, PROCEED_ITEM_MOBILE_MENU, STOCK_MOBILE_MENU, STOCK_MOVEMENT_MOBILE_MENU]),
)

PICKER_CHECKER_GROUP_NAME = ['Picker', 'Checker']


# user group
UG_SALES = "Sales"
