
WAITING = 'waiting'
ON_PROGRESS = 'on_progress'
ARRIVED = 'arrived'
COMPLETED = 'completed'
SKIPPED = 'skipped'

VAT_DEFAULT = 0.11

CANVASING_MOBILE_MENU = 'sales_canvasing'
TAKING_ORDER_MOBILE_MENU = 'sales_taking_order'
SALES_ORDER_MOBILE_MENU = 'sales_order'
CUSTOMER_MOBILE_MENU = 'customer'
PICKER_MOBILE_MENU = 'picker'
CHECKER_MOBILE_MENU = 'checker'
STOCK_MOBILE_MENU = 'stock'
DELIVERY_MOBILE_MENU = 'delivery'
COLLECTION_MOBILE_MENU = 'collection'
MOBILE_ROLE_MENU_MAP = (
    ('sales-canvasing', [CANVASING_MOBILE_MENU, SALES_ORDER_MOBILE_MENU, CUSTOMER_MOBILE_MENU, STOCK_MOBILE_MENU]),
    ('sales-taking-order', [TAKING_ORDER_MOBILE_MENU, SALES_ORDER_MOBILE_MENU, CUSTOMER_MOBILE_MENU, STOCK_MOBILE_MENU]),
    ('picker', [PICKER_MOBILE_MENU, STOCK_MOBILE_MENU]),
    ('checker', [CHECKER_MOBILE_MENU, STOCK_MOBILE_MENU]),
    ('driver', [DELIVERY_MOBILE_MENU]),
    ('collector', [COLLECTION_MOBILE_MENU]),
)