# Generated by Django 4.2.3 on 2023-07-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_account_owned_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='financialentry',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='financialstatement',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='generalledger',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='journalentry',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='id62',
            new_name='id32',
        ),
    ]
