# Generated by Django 4.2.3 on 2023-11-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_account_approved_by_alter_account_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Purchase', 'Purchase'), ('Transfer', 'Transfer'), ('Adjustment', 'Adjustment'), ('Expense', 'Expense'), ('Income', 'Income'), ('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Refund', 'Refund'), ('Reconciliation', 'Reconciliation'), ('Loan Payment', 'Loan Payment'), ('Loan Receipt', 'Loan Receipt'), ('Tax Payment', 'Tax Payment'), ('Tax Refund', 'Tax Refund'), ('Interest Income', 'Interest Income'), ('Interest Expense', 'Interest Expense'), ('Dividend', 'Dividend'), ('Fee', 'Fee'), ('Commission', 'Commission'), ('Write Off', 'Write Off'), ('Other', 'Other')], default='OTHER', max_length=20),
        ),
    ]
