# Generated by Django 4.2.3 on 2023-11-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
