# Generated by Django 4.2.3 on 2023-11-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_generalledger_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
