# Generated by Django 4.2.3 on 2023-11-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
