# Generated by Django 4.2.3 on 2023-11-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_financialentry_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='generate_journal',
            field=models.BooleanField(default=True),
        ),
    ]
