# Generated by Django 4.2.3 on 2024-02-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_transaction_generate_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_id32',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
