# Generated by Django 4.2.3 on 2024-04-01 22:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0014_alter_journalentry_debit_credit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='AccountCategory',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['number'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountcategory',
            options={'ordering': ['number'], 'verbose_name': 'AccountCategory', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='financialentry',
            options={'ordering': ['-id'], 'verbose_name': 'Financial Entry', 'verbose_name_plural': 'Financial Entries'},
        ),
        migrations.AlterModelOptions(
            name='financialstatement',
            options={'ordering': ['-id'], 'verbose_name': 'Financial Statement', 'verbose_name_plural': 'Financial Statements'},
        ),
        migrations.AlterModelOptions(
            name='generalledger',
            options={'ordering': ['-id'], 'verbose_name': 'General Ledger', 'verbose_name_plural': 'General Ledgers'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-id'], 'verbose_name': 'Journal Entry', 'verbose_name_plural': 'Journal Entries'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
