# Generated by Django 4.2.3 on 2024-04-01 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_accountcategory_options_transactioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='code',
            field=models.CharField(default='default', help_text='Enter the category code', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.transactioncategory'),
        ),
    ]
