# Generated by Django 4.2.3 on 2024-04-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_transactioncategory_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='prefix',
            field=models.CharField(blank=True, help_text='Enter the category prefix', max_length=20, null=True),
        ),
    ]
