# Generated by Django 4.2.3 on 2024-04-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_moduleaccount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moduleaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='moduleaccount',
            name='transaction',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase')], default='default', help_text='Enter the transaction', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moduleaccount',
            name='name',
            field=models.CharField(help_text='Enter the module account name', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='moduleaccount',
            unique_together={('transaction', 'account')},
        ),
    ]
