# Generated by Django 4.2.3 on 2024-04-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_alter_moduleaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleaccount',
            name='transaction',
            field=models.CharField(choices=[('sales_order', 'Sales Order'), ('sales_payment', 'Sales Payment'), ('purchase', 'Purchase')], help_text='Enter the transaction', max_length=25),
        ),
    ]
