# Generated by Django 4.2.3 on 2024-04-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_moduleaccount_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleaccount',
            name='name',
            field=models.CharField(choices=[('sales_order_credit', 'Sales order credit'), ('sales_order_debit', 'Sales order debit')], help_text='Enter the module account name', max_length=100, unique=True),
        ),
    ]
