# Generated by Django 4.2.3 on 2024-04-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_financialstatement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='inverse_debit_credit',
            field=models.BooleanField(default=False),
        ),
    ]
