# Generated by Django 4.2.3 on 2024-04-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_account_inverse_debit_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialentry',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
