# Generated by Django 4.2.3 on 2024-04-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_remove_financialentry_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialentry',
            name='account',
        ),
        migrations.RemoveField(
            model_name='financialreportentry',
            name='account',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='accounts',
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='categories',
            field=models.ManyToManyField(through='accounting.FinancialEntry', to='accounting.accountcategory'),
        ),
        migrations.AlterField(
            model_name='financialreportentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
