# Generated by Django 4.2.3 on 2024-04-18 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_remove_financialentry_account_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialreport',
            unique_together={('financial_statement', 'start_date', 'end_date')},
        ),
    ]
