# Generated by Django 4.2.3 on 2024-04-20 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0004_delete_companyprofile_contact_approved_by_and_more'),
        ('accounting', '0030_alter_financialentry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='origin_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='origin_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identities.contact'),
        ),
    ]
