# Generated by Django 4.2.3 on 2024-04-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_remove_transaction_origin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(blank=True, help_text='Enter account number', max_length=20, null=True, unique=True),
        ),
    ]
