# Generated by Django 4.2.3 on 2024-04-20 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_alter_file_file'),
        ('accounting', '0032_alter_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_attachment', to='common.file'),
        ),
    ]
