# Generated by Django 4.2.3 on 2024-04-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_transaction_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='attachements',
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='code',
            field=models.CharField(help_text='Enter the category code', max_length=100),
        ),
    ]
