# Generated by Django 4.2.3 on 2024-04-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_remove_transaction_attachements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleaccount',
            name='name',
            field=models.CharField(choices=[('sales_order_credit', 'Sales order credit'), ('sales_order_debit', 'Sales order debit'), ('sales_advance_payment', 'Sales advance payment'), ('sales_order_debit', 'Purchasing advance payment')], help_text='Enter the module account name', max_length=100, unique=True),
        ),
    ]
