# Generated by Django 4.2.3 on 2023-09-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customervisit',
            options={'verbose_name': 'Customer Visit', 'verbose_name_plural': 'Customer Visits'},
        ),
        migrations.AlterModelOptions(
            name='customervisitreport',
            options={'verbose_name': 'Customer Visit Report', 'verbose_name_plural': 'Customer Visit Reports'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AlterModelOptions(
            name='tripcustomer',
            options={'ordering': ['order'], 'verbose_name': 'Trip Customer', 'verbose_name_plural': 'Trip Customers'},
        ),
        migrations.AlterModelOptions(
            name='triptemplate',
            options={'verbose_name': 'Trip Template', 'verbose_name_plural': 'Trip Templates'},
        ),
    ]
