# Generated by Django 4.2.3 on 2023-07-11 10:12

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('identities', '0002_companyprofile_approved_at_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(help_text='Enter the address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_profile',
            field=models.ForeignKey(help_text='Select the company profile associated with the customer', on_delete=django.db.models.deletion.CASCADE, related_name='customers_profile', to='identities.companyprofile', verbose_name='Company Profile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(help_text='Enter the contact number', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Enter the location coordinates', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text="Enter the customer's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Specify the date and time of approval', null=True, verbose_name='Approved at'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Select the user who approved the invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sales_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(help_text='Enter the invoice date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(help_text='Select the order associated with the invoice', on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='Select the order associated with the item', on_delete=django.db.models.deletion.CASCADE, to='sales.salesorder'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the item price in IDR (Rp)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(help_text='Select the product associated with the item', on_delete=django.db.models.deletion.CASCADE, to='sales.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Enter the item quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Enter the product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text="Enter the product's name", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the product price in IDR (Rp)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(help_text='Enter the product quantity'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Specify the date and time of approval', null=True, verbose_name='Approved at'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Select the user who approved the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(help_text='Select the customer associated with the order', on_delete=django.db.models.deletion.CASCADE, to='sales.customer'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(help_text='Enter the order date'),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter the payment amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Specify the date and time of approval', null=True, verbose_name='Approved at'),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Select the user who approved the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sales_payments', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='invoice',
            field=models.ForeignKey(help_text='Select the invoice associated with the payment', on_delete=django.db.models.deletion.CASCADE, to='sales.invoice'),
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='payment_date',
            field=models.DateField(help_text='Enter the payment date'),
        ),
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(help_text='Enter the quantity change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sales.product')),
            ],
            options={
                'verbose_name': 'Product Log',
                'verbose_name_plural': 'Product Logs',
            },
        ),
    ]
