# Generated by Django 4.2.3 on 2023-09-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_customervisit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='type',
            field=models.CharField(choices=[('canvasing', 'Canvasing'), ('taking_order', 'Taking Order'), ('collecting', 'Collecting'), ('delivering', 'Delivering')], default='taking_order', max_length=50),
        ),
    ]
