# Generated by Django 4.2.3 on 2023-09-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_administrativelvl4_name'),
        ('sales', '0004_alter_customer_company_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='administrative_lv1',
            field=models.ForeignKey(blank=True, help_text='Enter the  Administrative Lvl 1', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.administrativelvl1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='administrative_lv2',
            field=models.ForeignKey(blank=True, help_text='Enter the  Administrative Lvl 2', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.administrativelvl2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='administrative_lv3',
            field=models.ForeignKey(blank=True, help_text='Enter the  Administrative Lvl 3', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.administrativelvl3'),
        ),
        migrations.AddField(
            model_name='customer',
            name='administrative_lv4',
            field=models.ForeignKey(blank=True, help_text='Enter the  Administrative Lvl 4', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.administrativelvl4'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cbd', 'Cash before Delivery'), ('cod', 'Cash on Delivery'), ('credit', 'Credit')], help_text='Select payment type.', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='r2',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='rt',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='store_name',
            field=models.CharField(blank=True, help_text='Enter the store name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='store_type',
            field=models.CharField(blank=True, choices=[('wholesaler', 'Wholesaler'), ('distributor', 'Distributor'), ('retailer', 'Retailer')], help_text='Select store type.', max_length=25, null=True),
        ),
    ]
