# Generated by Django 4.2.3 on 2023-07-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_orderitem_product_alter_productlog_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLog',
        ),
    ]
