# Generated by Django 4.2.3 on 2023-09-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customer_administrative_lv1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='r2',
            new_name='rw',
        ),
    ]
