# Generated by Django 4.2.3 on 2023-07-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_customer_owned_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='id62',
            new_name='id32',
        ),
        migrations.RenameField(
            model_name='salespayment',
            old_name='id62',
            new_name='id32',
        ),
    ]
