# Generated by Django 4.2.3 on 2023-07-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_stockmovement_product_and_more'),
        ('sales', '0007_rename_id62_customer_id32_rename_id62_invoice_id32_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stockmovement'),
        ),
    ]
