# Generated by Django 4.2.3 on 2023-08-07 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_product_alias_product_brand_product_minimum_quantity_and_more'),
        ('sales', '0008_salesorder_stock_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='Select the order associated with the item', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', related_query_name='orderitem', to='sales.salesorder'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockmovement'),
        ),
    ]
