# Generated by Django 4.2.3 on 2023-08-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_canvasingcustomer_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasingcustomervisit',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order of customer visit in the trip', verbose_name='Order'),
            preserve_default=False,
        ),
    ]
