# Generated by Django 4.2.3 on 2023-10-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespayment',
            name='status',
            field=models.CharField(choices=[('authorize', 'Authorize: The payment has been authorized but not yet captured.'), ('capture', 'Capture: The authorized payment has been secured.'), ('settlement', 'Settlement: The payment process has been completed and funds have been transferred.'), ('deny', 'Deny: The payment request was denied.'), ('pending', 'Pending: The payment process is ongoing and the final status is not yet determined.'), ('cancel', 'Cancel: The payment process was canceled before completion.'), ('refund', 'Refund: Funds have been returned to the payer.'), ('expired', 'Expired: The payment authorization has expired without capture.'), ('falure', 'Failure: The payment process encountered an error and was unsuccessful.')], default='pending', help_text='Current status of the payment.', max_length=255),
        ),
    ]
