# Generated by Django 4.2.3 on 2023-08-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_canvasingcustomervisit_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvasingcustomer',
            options={'ordering': ['order'], 'verbose_name': 'Canvassing Customer', 'verbose_name_plural': 'Canvassing Customers'},
        ),
        migrations.AlterModelOptions(
            name='canvasingcustomerproduct',
            options={'verbose_name': 'Canvassing Customer Product', 'verbose_name_plural': 'Canvassing Customer Products'},
        ),
        migrations.AlterModelOptions(
            name='canvasingcustomervisit',
            options={'verbose_name': 'Canvassing Customer Visit', 'verbose_name_plural': 'Canvassing Customer Visits'},
        ),
        migrations.AlterModelOptions(
            name='canvasingreport',
            options={'verbose_name': 'Canvassing Report', 'verbose_name_plural': 'Canvassing Reports'},
        ),
        migrations.AlterModelOptions(
            name='canvasingtrip',
            options={'verbose_name': 'Canvassing Trip', 'verbose_name_plural': 'Canvassing Trips'},
        ),
        migrations.AlterModelOptions(
            name='canvasingtriptemplate',
            options={'verbose_name': 'Canvassing Trip Template', 'verbose_name_plural': 'Canvassing Trip Templates'},
        ),
    ]
