# Generated by Django 4.2.3 on 2023-10-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_salespayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='type',
            field=models.CharField(choices=[('canvasing', 'Canvasing'), ('taking_order', 'Taking Order')], default='taking_order', max_length=50),
        ),
    ]
