# Generated by Django 4.2.3 on 2023-08-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_canvasingcustomer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', "Draft: The initial stage of the order where it's still being drafted or created."), ('submitted', 'Submitted: Order has been completed and sent for review or approval.'), ('approved', 'Approved: Order has been accepted for processing after review.'), ('rejected', 'Rejected: Order has been found unsuitable for processing and needs revision.'), ('processing', 'Processing: Active steps to fulfill the order are underway.'), ('shipped', 'Shipped: Order has left the business premises and is en route to the customer.'), ('delivered', 'Delivered: Order has reached its destination and is now with the customer.'), ('completed', "Completed: All aspects of the order are done, and it's considered closed."), ('canceled', 'Canceled: Order was terminated before reaching completion.')], default='draft', help_text='Current status of the sales order.', max_length=255),
        ),
    ]
