# Generated by Django 4.2.3 on 2023-10-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_invoice_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='invoice_pdf_generated',
            field=models.BooleanField(default=False),
        ),
    ]
