# Generated by Django 4.2.3 on 2023-10-13 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_administrativelvl4_name'),
        ('sales', '0016_salesorder_invoice_pdf_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='customervisit',
            name='item_delivery_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_item_delivery_evidence', to='common.file'),
        ),
    ]
