# Generated by Django 4.2.3 on 2023-10-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_triptemplate_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customervisit',
            options={'ordering': ['-id'], 'verbose_name': 'Customer Visit', 'verbose_name_plural': 'Customer Visits'},
        ),
        migrations.AlterModelOptions(
            name='customervisitreport',
            options={'ordering': ['-id'], 'verbose_name': 'Customer Visit Report', 'verbose_name_plural': 'Customer Visit Reports'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-id'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-id'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='salespayment',
            options={'ordering': ['-id'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-id'], 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AlterModelOptions(
            name='triptemplate',
            options={'ordering': ['-id'], 'verbose_name': 'Trip Template', 'verbose_name_plural': 'Trip Templates'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_type',
            field=models.CharField(choices=[('cbd', 'Cash before Delivery'), ('cod', 'Cash on Delivery'), ('credit', 'Credit')], default='cbd', help_text='Select payment type.', max_length=25),
        ),
    ]
