# Generated by Django 4.2.3 on 2023-10-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_alter_customer_approved_by_alter_customer_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter the payment amount', max_digits=19),
        ),
    ]
