# Generated by Django 4.2.3 on 2023-10-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_alter_salespayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_delivery_processed',
            field=models.BooleanField(default=False),
        ),
    ]
