# Generated by Django 4.2.3 on 2023-10-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_remove_job_stock_movement_job_trip'),
        ('sales', '0024_trip_is_delivery_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptemplate',
            name='vehicles',
            field=models.ManyToManyField(blank=True, help_text='Select vehicles prefered for this trip', to='logistics.vehicle'),
        ),
    ]
