# Generated by Django 4.2.3 on 2023-11-12 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0027_remove_salesorder_trip_salesorder_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptemplate',
            name='collector_pic',
            field=models.ManyToManyField(blank=True, help_text='Select people in charge of this trip', related_name='%(app_label)s_%(class)s_collector_pic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.CharField(choices=[('canvasing', 'Canvasing'), ('taking_order', 'Taking Order'), ('collecting', 'Collecting')], default='taking_order', max_length=50),
        ),
        migrations.AlterField(
            model_name='triptemplate',
            name='pic',
            field=models.ManyToManyField(blank=True, help_text='Select people in charge of this trip', related_name='%(app_label)s_%(class)s_pic', to=settings.AUTH_USER_MODEL),
        ),
    ]
