# Generated by Django 4.2.3 on 2023-11-12 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0028_triptemplate_collector_pic_alter_trip_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(help_text='Date for the trip', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_salesperson', to=settings.AUTH_USER_MODEL),
        ),
    ]
