# Generated by Django 4.2.3 on 2023-11-12 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0029_trip_parent_alter_trip_date_alter_trip_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='collector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_collector', to=settings.AUTH_USER_MODEL),
        ),
    ]
