# Generated by Django 4.2.3 on 2023-11-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_alter_invoice_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter the item price in IDR (Rp)', max_digits=19),
        ),
    ]
