# Generated by Django 4.2.3 on 2024-02-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cbd', 'Cash before Delivery'), ('cod', 'Cash on Delivery'), ('credit', 'Credit')], default='cbd', help_text='Select payment type.', max_length=25, null=True),
        ),
    ]
