# Generated by Django 4.2.3 on 2024-03-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_remove_customer_store_type_storetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.storetype'),
        ),
    ]
