# Generated by Django 4.2.3 on 2024-03-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_product_price_calculation'),
        ('sales', '0037_customer_store_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='stock_movement',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='stock_movements',
            field=models.ManyToManyField(blank=True, to='inventory.stockmovement'),
        ),
    ]
