# Generated by Django 4.2.3 on 2024-05-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0040_alter_customer_address_alter_customer_contact_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="bonus",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Enter the bonus amount",
                max_digits=19,
            ),
        ),
    ]
