# Generated by Django 4.2.3 on 2024-05-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_salesorder_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter the DP amount', max_digits=19),
        ),
    ]
