# Generated by Django 4.2.3 on 2024-04-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_customer_has_receivable_alter_invoice_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recievable',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter receivable amount', max_digits=19),
            preserve_default=False,
        ),
    ]
