# Generated by Django 4.2.3 on 2024-06-06 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0042_salesorder_down_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="OQMDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("daily_omzet", models.DecimalField(decimal_places=2, max_digits=19)),
                ("daily_quantity", models.IntegerField()),
                ("daily_margin", models.DecimalField(decimal_places=2, max_digits=19)),
                (
                    "daily_margin_percentage",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "verbose_name": "OQM Daily",
                "verbose_name_plural": "OQM Dailies",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SellingMarginDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("daily_margin", models.DecimalField(decimal_places=2, max_digits=19)),
                (
                    "sales",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
