# Generated by Django 4.2.3 on 2024-04-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_receivable_delete_recievable'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
