# Generated by Django 4.2.3 on 2024-04-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, help_text='Enter the invoice due date', null=True),
        ),
    ]
